services:
    postgres:
        image: postgres:14.6-alpine
        environment:
            POSTGRES_DB: "bookcrossing"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123456"
        ports:
            - "5432:5432"